include ../../../base.make

all: CLM.o FCheck.o FDet.o IO.o Patch.o PAW.o PDM.o Tracker.o

CLM.o: CLM.cpp CLM.h
	$(CC) $(CFLAGS) CLM.cpp

FCheck.o: FCheck.cpp FCheck.h
	$(CC) $(CFLAGS) FCheck.cpp

FDet.o: FDet.cpp FDet.h
	$(CC) $(CFLAGS) FDet.cpp

IO.o: IO.cpp IO.h
	$(CC) $(CFLAGS) IO.cpp

Patch.o: Patch.cpp Patch.h
	$(CC) $(CFLAGS) Patch.cpp

PAW.o: PAW.cpp PAW.h
	$(CC) $(CFLAGS) PAW.cpp

PDM.o: PDM.cpp PDM.h
	$(CC) $(CFLAGS) PDM.cpp

Tracker.o: Tracker.cpp Tracker.h
	$(CC) $(CFLAGS) Tracker.cpp

